fix: Handling case when parser returned a tuple instead of CompassDoc… (#168)
…umnet

## Description
We used to throw Attribute Error when process folder and insert doc was
used
```
AttributeError: 'tuple' object has no attribute 'status'
  File .../cohere_compass/clients/compass.py:852 in insert_docs
    Parallel(n_jobs=num_jobs, backend="threading")( ... )
  File .../joblib/parallel.py:1986 in __call__
  ...
  File .../cohere_compass/clients/compass.py:280
    f"Document {doc.metadata.document_id} has errors: {doc.errors}"
```

This happened due to incorrect handling of tuple in `process_folder`.

This PR handles the tuple in `insert_docs` step. An error is not
intentionally raised in parser to allow parallelism and let it yield
results

BEFORE:
Processing is stopped when the error is encountered
<img width="1145" height="200" alt="Screenshot 2025-11-21 at 19 57 55"
src="https://github.com/user-attachments/assets/78b919c4-3c17-4db3-b454-40b3616ece52"
/>

AFTER:
Error is logged but other documents are processed
<img width="1130" height="221" alt="Screenshot 2025-11-21 at 19 56 58"
src="https://github.com/user-attachments/assets/c4159a9b-e3b9-40ac-a0e9-6d549bc34490"
/>