require python >= 3.11 (#37)
With python < 3.11 we get : 
```
[Python Enum AttributeError: module 'enum' has no attribute 'StrEnum'](https://stackoverflow.com/questions/75850073/python-enum-attributeerror-module-enum-has-no-attribute-strenum)
```

Requires minimum python 3.11

Signed-off-by: d-rau <davidrau@cohere.com>